### ISSUE TITLE
SignInAsync verifyHashpassword

### ISSUE THREAD

**Issue by pMonfared** [rabbal/DNTFrameworkCoreTemplate#3]
I try to login with Admin user from seeduser information but i get this error :

Curl request details:
```
curl -X POST "https://localhost:6001/api/Auth/Login" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"userName\": \"Admin\", \"password\": \"123@456#Pass\"}"
```

![image](https://user-images.githubusercontent.com/10448255/54078803-ec3de700-42e3-11e9-84bf-d07830152708.png)

[at this line ](https://github.com/rabbal/DNTFrameworkCoreTemplate/blob/ceae1d3b24ef22a04020162dd4de9e85cb772c43/DNTFrameworkCoreTemplateAPI/src/DNTFrameworkCoreTemplateAPI.API/Authentication/AuthenticationService.cs#L56)

**Comment by rabbal** [comment]
In development environment, [password is 123456](https://github.com/rabbal/DNTFrameworkCoreTemplate/blob/master/DNTFrameworkCoreTemplateAPI/src/DNTFrameworkCoreTemplateAPI.API/appsettings.Development.json#L16).
