### ISSUE TITLE
Command Not working

### ISSUE THREAD

**Issue by sandeep-bhaskar** [rabbal/DNTFrameworkCoreTemplate#5]
Getting error while trying to execute the initializing command **dotnet new --install DNTFrameworkCoreTemplateAPI::*‌‌**
![image](https://user-images.githubusercontent.com/27012859/70523351-e160fd00-1b68-11ea-84ac-41df622e1459.png)

**Comment by MrXemiu** [comment]
I had issues installing this with the dotnet new --install command as well.  In my case I had to specify the nuget repostory explicitly:
![image](https://user-images.githubusercontent.com/4266607/75566928-dc944280-5a0d-11ea-9757-003d698080e4.png)

Then I had to install the template from the nuget package that was downloaded:
![image](https://user-images.githubusercontent.com/4266607/75566853-ac4ca400-5a0d-11ea-9791-ba491a6b0d1b.png)

**Comment by davidcateduclarity** [comment]
What a shame... All this work and it can't be installed...

**Comment by amir-ashy** [comment]
the following command  will be working:

`dotnet new --install DNTFrameworkCoreTemplateAPI::3.6.1`

**Comment by rabbal** [comment]
Try to install new version of this template via: dotnet new --install DNTFrameworkCoreTemplateAPI::5.1.0
